server:
  port: 8000

spring:
  application:
    name: quick-dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hadoop001:3306/iot_platform?serverTimezone=Asia/Shanghai&useUnicode=true
    username: root
    password: 123456
  redis:
    database: 0
    host: hadoop002
    port: 6379
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

mybatis:
  configuration:
    # 字段和实体成员的映射，支持驼峰规则
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: com.example.quickdev.entity

logging:
  level:
    com.example.quickdev.mapper: debug

jwt:
  secretKey: secretKey
  subject: sub
  expire: 3600




